version: '3.8'

services:
  postgres_db:
    image: postgres:15
    container_name: client_server_postgres
    environment:
      POSTGRES_DB: client_server_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./Database/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app_user -d client_server_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
